const AUTH_STATES = {
    UNAUTHETICATED: "UNAUTHENTICATED",
    USER_EMAIL_INVALID: "USER_EMAIL_INVALID",
    NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
    AUTHENTICATED: "AUTHENTICATED",
    NEED_DOUBLE_AUTH: "NEED_DOUBLE_AUTH",
    CODE_SENT: "CODE_SENT",
    CODE_INCORRECT: "CODE_INCORRECT",
    CODE_EXPIRED: "CODE_EXPIRED",
    ERRORED: "ERRORED",
    NONEED_TOBE_SECURED: "NONEEDTOBESECURED",
    ALREADYSECURED: "ALREADYSECURED",
}
export default AUTH_STATES;